const ERROR_CODE_VALIDATION = 400;
const ERROR_CODE_UNAUTHORIZED = 401;
const ERROR_CODE_FORBIDDEN = 403;
const ERROR_CODE_NOT_FOUND = 404;
const ERROR_CODE_EXIST_EMAIL = 409;
const ERROR_CODE_DEFAULT = 500;

module.exports = {
  ERROR_CODE_VALIDATION,
  ERROR_CODE_UNAUTHORIZED,
  ERROR_CODE_FORBIDDEN,
  ERROR_CODE_NOT_FOUND,
  ERROR_CODE_EXIST_EMAIL,
  ERROR_CODE_DEFAULT,
};
